package com.googlesource.gerrit.plugins.aicodereview.settings;

import java.util.Map;

public class Settings {
  public static final String GERRIT_PATCH_SET_FILENAME = "/PATCHSET_LEVEL";
  public static final String GERRIT_DEFAULT_MESSAGE_DONE = "Done";
  public static final String GERRIT_AUTOGENERATED_PREFIX = "autogenerated:";
  public static final Map<String, String> COMMIT_MESSAGE_FILTER_OUT_PREFIXES =
      Map.of(
          "PARENT", "Parent:",
          "AUTHOR", "Author:",
          "AUTHOR_DATE", "AuthorDate:",
          "COMMIT", "Commit:",
          "COMMIT_DATE", "CommitDate:",
          "CHANGE_ID", "Change-Id:");
  public static final String GERRIT_COMMIT_MESSAGE_PREFIX = "Subject: ";

  public static final String OPEN_AI_CHAT_ROLE_USER = "user";
  public static final String OPEN_AI_CHAT_ROLE_ASSISTANT = "assistant";

  public enum Modes {
    stateless,
    stateful
  }

  public enum AIType {
    CHATGPT,
    OLLAMA,
    AZUREOPENAI,

    // used for testing new endpoints and ai services not yet in the supported list, but you can
    // specify the
    // endpoint, the authorization header information, and the prompt to quickly prove out a new
    // aiType.
    GENERIC;
  }
}
